### PR TITLE
Remove out-most directory

### PR DESCRIPTION
**Pull request by leyuan**
This PR got rid of the un-needed folder that was wrapping the react native project.

I think the github PR template is not working.. Need to investigate..

### CODE REVIEW

**Comment by leyuan** [comment]
this is a big boy pr needs QA

**Comment by whr0002** [comment]
我估计最外层的node_modules没用  你问问爽吧

**Comment by leyuan** [comment]
@whr0002 我问过了最外一层的是最开始setup错了，所以我把里面的东西都拿出来了

cc @AaronLiuIsCool

**Comment by whr0002** [comment]
你就没用 merge吧

**Pull request merged**
